<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Answer Key - {{ $quiz->topic_name }}</title>
    <style>
        /* Clean and simple answer key design */
        body {
            font-family: 'DejaVu Sans', Arial, sans-serif;
            line-height: 1.6;
            color: #222;
            margin: 30px 40px;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
            padding-bottom: 13px;
            border-bottom: 3px solid #10b981;
        }

        .header h1 {
            margin: 0 0 8px 0;
            color: #059669;
            font-size: 28px;
            font-weight: bold;
            letter-spacing: 2px;
        }

        .header h2 {
            margin: 0;
            color: #64748b;
            font-size: 16px;
            font-weight: normal;
        }

        .confidential {
            background-color: #fee2e2;
            border: 2px solid #dc2626;
            padding: 15px;
            margin-bottom: 25px;
            text-align: center;
        }

        .confidential p {
            margin: 5px 0;
            color: #991b1b;
            font-weight: bold;
            font-size: 14px;
        }

        .info-box {
            background-color: #f0fdf4;
            padding: 10px 15px;
            margin-bottom: 20px;
            border-left: 4px solid #10b981;
            font-size: 13px;
        }

        .info-box p {
            margin: 4px 0;
            color: #166534;
        }

        .info-box strong {
            color: #14532d;
        }

        /* Simple answer list - EXACTLY like your format */
        .answer-section {
            margin: 12px 0;
        }

        .answer-section h3 {
            color: #059669;
            font-size: 18px;
            margin-bottom: 10px;
            padding-bottom: 6px;
            border-bottom: 2px solid #d1fae5;
        }

        .simple-answers {
            background-color: #ffffff;
            padding: 20px;
            border: 2px solid #10b981;
            border-radius: 5px;
        }

        .answer-line {
            font-size: 15px;
            margin: 8px 0;
            padding: 8px 12px;
            background-color: #f0fdf4;
            border-left: 4px solid #10b981;
            font-family: 'Courier New', monospace;
        }

        .answer-number {
            font-weight: bold;
            color: #059669;
            display: inline-block;
            min-width: 35px;
        }

        .answer-letter {
            font-weight: bold;
            color: #14532d;
            font-size: 16px;
        }

       
        .footer {
            margin-top: 40px;
            padding-top: 15px;
            border-top: 2px solid #e2e8f0;
            text-align: center;
            font-size: 11px;
            color: #64748b;
        }
    </style>
</head>

<body>

    <!-- Header -->
    <div class="header">
        <h1>ANSWER KEY</h1>
        <h2>{{ $quiz->topic_name }}</h2>
    </div>

    <!-- Confidential Warning -->
    <div class="confidential">
        <p>⚠️ CONFIDENTIAL - FOR INSTRUCTOR USE ONLY ⚠️</p>
        <p>Do not distribute to students before exam</p>
    </div>

    <!-- Info Box -->
    <div class="info-box">
        <p><strong>University:</strong> {{ $quiz->university_name }}</p>
        <p><strong>Topic:</strong> {{ $quiz->topic_name }}</p>
        <p><strong>Total Questions:</strong> {{ $quiz->num_questions }}</p>
        <p><strong>Generated:</strong> {{ now()->format('F d, Y h:i A') }}</p>
    </div>

    <!-- SIMPLE ANSWER LIST (Main Section) -->
    <div class="answer-section">
        <h3>📝 Correct Answers</h3>

        <div class="simple-answers">
            @foreach ($quiz->questions as $index => $question)
                <div class="answer-line">
                    <span class="answer-number">{{ $index + 1 }}.</span>
                    <span class="answer-letter">{{ strtoupper($question['correct_answer']) }}</span>
                </div>
            @endforeach
        </div>
    </div>


    <!-- Footer -->
    <div class="footer">
        <p><strong>Generated by LecToQuiz Converter</strong></p>
        <p>This answer key is automatically generated using AI</p>
        <p>&copy; {{ date('Y') }} All Rights Reserved</p>
    </div>

</body>

</html>
